title: "Portfolio Hardware"
description: "Portfolio personale di progetti hardware"
author: "Stefano"
url: ""
baseurl: "/personal-portfolio"

permalink: pretty

collections:
  projects:
    output: true
    permalink: /projects/:name/

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

markdown: kramdown
